---
- name: Copy MySQL configuration
  template:
    src: my.cnf.j2
    dest: '/etc/mysql/my.cnf'
    owner: root
    group: root
    mode: '0644'
  notify: restart mysql

- name: Start MySQL
  service:
    name: 'mysql'
    state: started

- name: Enable MySQL
  when: mysql_enable
  service:
    name: 'mysql'
    enabled: 'yes'

- name: Copy .my.cnf
  template:
    src: '.my.cnf.j2'
    dest: '/root/.my.cnf'
    owner: root
    group: root
    mode: '0600'

- name: Set root password
  mysql_user:
    name: root
    host: '{{ item }}'
    password: '{{ mysql_root_password | mandatory }}'
    state: present
  with_items:
    - '{{ mysql_root_hosts }}'
  no_log: true

- name: Copy database dump file
  when: mysql_use_dump
  copy:
    src: '{{ mysql_db_file | mandatory }}'
    dest: /tmp

- name: Restore database
  when: mysql_use_dump
  mysql_db:
    name: '{{ mysql_db_name | mandatory }}'
    state: import
    target: '/tmp/{{ mysql_db_file | mandatory }}'

- name: Create non-root user
  when: mysql_non_root_user
  mysql_user:
    name: '{{ mysql_non_root_user_name | mandatory }}'
    host: '{{ item }}'
    password: '{{ mysql_non_root_user_password }}'
    priv: '{{ mysql_non_root_user_privs }}'
    state: present
  with_items:
    - '{{ mysql_non_root_user_hosts }}'
  no_log: true

- name: Remove test database
  when: mysql_remove_testdb
  mysql_db:
    name: test
    state: absent

- name: Remove anonymous users
  mysql_user:
    name: ''
    state: absent
    host_all: yes
  no_log: true

- name: Bind to interface(s)
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = {{ mysql_bind_addr | mandatory }}'
  notify: restart mysql

- name: Check if SSL is enabled
  when: mysql_check_ssl
  mysql_info:
    login_user: root
    filter: settings
  register: ssl
  failed_when: >
    ('have_openssl:\": \"\"' in ssl.settings) or
    ('have_ssl:\": \"\"' in ssl.settings) or
    ('ssl_ca:\": \"\"' in ssl.settings) or
    ('ssl_cert:\": \"\"' in ssl.settings) or
    ('ssl_key:\": \"\"' in ssl.settings)
